---
all:
  children:
    gitlab_servers:
      hosts:
        gitlab-01:
          ansible_host: "192.168.10.10"
    gitlab_runners:
      hosts:
        runner-01:
          ansible_host: "192.168.10.21"
          gitlab_runner_profile: "general"
        runner-02:
          ansible_host: "192.168.10.22"
          gitlab_runner_profile: "container-build"
        runner-03:
          ansible_host: "192.168.10.23"
          gitlab_runner_profile: "deploy"
