---
# GitLab Runner Configuration for Local Lab

gitlab_runner_version: "19.3.1"
gitlab_runner_coordinator_url: "http://gitlab.192.168.56.10.nip.io"

# Concurrency for lab environment
gitlab_runner_concurrent: 2
gitlab_runner_check_interval: 5

# Docker Executor
gitlab_runner_executor: "docker"
gitlab_runner_default_image: "alpine:3.21"
gitlab_runner_privileged: false

# Automatically install Docker CE on the fresh Vagrant VM
gitlab_runner_install_docker: true
