---
all:
  vars:
    ansible_user: "vagrant"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  children:
    gitlab_servers:
      hosts:
        gitlab-01:
          ansible_host: "192.168.56.10"
    gitlab_runners:
      hosts:
        runner-01:
          ansible_host: "192.168.56.21"
          gitlab_runner_profile: "general"
