---
all:
  vars:
    ansible_user: "vagrant"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  children:
    gitlab_servers:
      hosts:
        gitlab-01:
          ansible_host: "192.168.56.10"
          ansible_ssh_private_key_file: "{{ inventory_dir }}/../../.vagrant/machines/gitlab-01/virtualbox/private_key"
    gitlab_runners:
      hosts:
        runner-01:
          ansible_host: "192.168.56.21"
          ansible_ssh_private_key_file: "{{ inventory_dir }}/../../.vagrant/machines/runner-01/virtualbox/private_key"
          gitlab_runner_profile: "general"
